version: "3.9"

services:
  nginx:
    image: nginx:1.21.6
    container_name: webserver
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/server.conf:/etc/nginx/conf.d/server.conf
